<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="2" failures="2" hostname="ubuntu" name="bixuan_suite" skipped="4" tests="16" time="0.100" timestamp="2020-02-23T23:41:00.199025"><testcase classname="test_PyTest_1" file="test_PyTest_1.py" line="5" name="test_mytest" time="0.001"></testcase><testcase classname="test_PyTest_2.TestClass" file="test_PyTest_2.py" line="2" name="test_one" time="0.001"></testcase><testcase classname="test_PyTest_2.TestClass" file="test_PyTest_2.py" line="6" name="test_two" time="0.001"></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="9" name="test_ok" time="0.002"><system-out>ok
</system-out></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="13" name="test_fail" time="0.001"><failure message="assert 0">def test_fail():
&gt;       assert 0
E       assert 0

test_PyTest_3.py:15: AssertionError</failure></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="17" name="test_error" time="0.001"><error message="test setup failure">@pytest.fixture
    def error_fixture():
&gt;       assert 0
E       assert 0

test_PyTest_3.py:7: AssertionError</error></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="21" name="test_skip" time="0.001"><skipped message="skipping this test" type="pytest.skip">/home/tanbixuan/PycharmProjects/pyTest/test_PyTest_3.py:23: skipping this test</skipped></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="25" name="test_xfail" time="0.001"><skipped message="xfailing this xfail" type="pytest.xfail"></skipped></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="29" name="test_xpass" time="0.001"></testcase><testcase classname="test_PyTest_4" file="test_PyTest_4.py" line="0" name="test_func" time="0.001"></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="9" name="test_ok" time="0.001"><system-out>ok
</system-out></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="13" name="test_fail" time="0.001"><failure message="assert 0">def test_fail():
&gt;       assert 0
E       assert 0

test_PyTest_3.py:15: AssertionError</failure></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="17" name="test_error" time="0.001"><error message="test setup failure">@pytest.fixture
    def error_fixture():
&gt;       assert 0
E       assert 0

test_PyTest_3.py:7: AssertionError</error></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="21" name="test_skip" time="0.001"><skipped message="skipping this test" type="pytest.skip">/home/tanbixuan/PycharmProjects/pyTest/test_PyTest_3.py:23: skipping this test</skipped></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="25" name="test_xfail" time="0.001"><skipped message="xfailing this xfail" type="pytest.xfail"></skipped></testcase><testcase classname="test_PyTest_3" file="test_PyTest_3.py" line="29" name="test_xpass" time="0.001"></testcase></testsuite></testsuites>